services:
  stable-diffusion:
    image: zefie/stable-diffusion-automatic1111:latest
    container_name: stable-diffusion
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      CLI_ARGS: >-
        --allow-code --xformers --enable-insecure-extension-access
        --api --disable-safe-unpickle --no-half-vae
    ports:
      - "7860:7860"
    volumes:
      - auto1111-data:/data
      - auto1111-output:/output
      - ./models:/models
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui-custom
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    restart: unless-stopped
    ports:
      - "3000:8080"

volumes:
  auto1111-data:
  auto1111-output:
  ollama:
  open-webui:
