services:
  stable-diffusion:
    image: zefie/stable-diffusion-automatic1111:latest
    container_name: stable-diffusion
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      CLI_ARGS: >-
        --allow-code --xformers --enable-insecure-extension-access
        --api --disable-safe-unpickle --no-half-vae
    ports:
      - "7860:7860"
    volumes:
      - auto1111-data:/data
      - auto1111-output:/output
      - ./models:/models
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui-custom
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      ENABLE_RAG_WEB_SEARCH: true
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 2
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 5
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>&format=json"

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - .env
    environment:
      SEARXNG_SEARCH_FORMATS: "html json"
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 open-webui
    depends_on:
      - open-webui

volumes:
  auto1111-data:
  auto1111-output:
  ollama:
  open-webui:
